const BUILTIN_LOCATIONS = [
  // ── Spyfall Classic ──────────────────────────────────────────────────────────
  {
    Location: 'Airplane', set: 'classic',
    Role1: 'Pilot', Role2: 'Co-Pilot', Role3: 'Flight Attendant',
    Role4: 'Passenger', Role5: 'Air Marshal', Role6: 'Mechanic',
    Role7: 'Baggage Handler', Role8: 'Boarding Agent', Role9: 'First Class Snob',
    Role10: 'Frequent Flyer', Role11: 'Nervous First-Timer', Role12: 'Middle Seat Victim',
    Role13: 'Crying Baby\'s Parent', Role14: 'Seat Recliner', Role15: 'Overhead Bin Hoarder', Role16: 'Immigration Officer'
  },
  {
    Location: 'Bank', set: 'classic',
    Role1: 'Bank Manager', Role2: 'Teller', Role3: 'Security Guard',
    Role4: 'Loan Officer', Role5: 'Customer', Role6: 'Robber',
    Role7: 'Vault Technician', Role8: 'Auditor', Role9: 'IT Specialist',
    Role10: 'Fraud Investigator', Role11: 'Janitor', Role12: 'Investment Advisor',
    Role13: 'Undercover Agent', Role14: 'Nervous First-Time Loan Applicant', Role15: 'Person Just Here to Break a $100', Role16: 'Mystery Safe Deposit Box Owner'
  },
  {
    Location: 'Beach', set: 'classic',
    Role1: 'Lifeguard', Role2: 'Surfer', Role3: 'Sunbather',
    Role4: 'Ice Cream Vendor', Role5: 'Volleyball Player', Role6: 'Scuba Diver',
    Role7: 'Parasailing Instructor', Role8: 'Beach Photographer', Role9: 'Marine Biologist',
    Role10: 'Jet Ski Operator', Role11: 'Metal Detectorist', Role12: 'Beach Patrol Officer',
    Role13: 'Sunburned Tourist', Role14: 'Seagull Victim', Role15: 'Food Truck Owner', Role16: 'Sandcastle Architect'
  },
  {
    Location: 'Broadway Theater', set: 'classic',
    Role1: 'Director', Role2: 'Lead Actor', Role3: 'Stage Manager',
    Role4: 'Costume Designer', Role5: 'Audience Member', Role6: 'Understudy',
    Role7: 'Set Designer', Role8: 'Lighting Technician', Role9: 'Sound Engineer',
    Role10: 'Choreographer', Role11: 'Makeup Artist', Role12: 'Ticket Seller',
    Role13: 'Props Master', Role14: 'Critic', Role15: 'Opening Night Nervous Wreck', Role16: 'Front Row Seat Stealer'
  },
  {
    Location: 'Casino', set: 'classic',
    Role1: 'Dealer', Role2: 'Pit Boss', Role3: 'High Roller',
    Role4: 'Cocktail Waitress', Role5: 'Security', Role6: 'Card Counter',
    Role7: 'Casino Manager', Role8: 'Croupier', Role9: 'Slot Technician',
    Role10: 'Surveillance Officer', Role11: 'Poker Champion', Role12: 'Cashier',
    Role13: 'Valet', Role14: 'Bartender', Role15: 'Compulsive Gambler on a Losing Streak', Role16: 'Person Who Came for the Free Drinks'
  },
  {
    Location: 'Cathedral', set: 'classic',
    Role1: 'Priest', Role2: 'Bishop', Role3: 'Nun',
    Role4: 'Choirboy', Role5: 'Wedding Guest', Role6: 'Tourist',
    Role7: 'Deacon', Role8: 'Organist', Role9: 'Acolyte',
    Role10: 'Bellringer', Role11: 'Pilgrim', Role12: 'Stained Glass Restorer',
    Role13: 'Confession Oversharer', Role14: 'Person Who Only Comes on Christmas', Role15: 'Reluctant Confirmation Student', Role16: 'Curious Atheist on a Tour'
  },
  {
    Location: 'Circus Tent', set: 'classic',
    Role1: 'Ringmaster', Role2: 'Acrobat', Role3: 'Clown',
    Role4: 'Lion Tamer', Role5: 'Tightrope Walker', Role6: 'Fire Breather',
    Role7: 'Magician', Role8: 'Contortionist', Role9: 'Strongman',
    Role10: 'Trapeze Artist', Role11: 'Juggler', Role12: 'Animal Trainer',
    Role13: 'Sword Swallower', Role14: 'Audience Volunteer Who Regrets It', Role15: 'Balloon Vendor', Role16: 'Stage Hand'
  },
  {
    Location: 'Corporate Party', set: 'classic',
    Role1: 'CEO', Role2: 'HR Manager', Role3: 'Intern',
    Role4: 'Finance Director', Role5: 'Party Planner', Role6: 'Caterer',
    Role7: 'Marketing Director', Role8: 'Sales VP', Role9: 'Board Member',
    Role10: 'IT Manager', Role11: 'Legal Counsel', Role12: 'Administrative Assistant',
    Role13: 'Security', Role14: 'Bartender', Role15: 'Person Who Wasn\'t Invited But Showed Up', Role16: 'Employee Already on Their Third Drink'
  },
  {
    Location: 'Crusader Army', set: 'classic',
    Role1: 'Knight', Role2: 'Archer', Role3: 'Squire',
    Role4: 'Siege Engineer', Role5: 'Field Surgeon', Role6: 'Camp Cook',
    Role7: 'Foot Soldier', Role8: 'Cavalry Commander', Role9: 'Chaplain',
    Role10: 'Crossbowman', Role11: 'Blacksmith', Role12: 'Spy',
    Role13: 'Quartermaster', Role14: 'Cowardly Deserter Who Got Caught', Role15: 'Reluctant Pilgrim', Role16: 'Lost Messenger'
  },
  {
    Location: 'Day Spa', set: 'classic',
    Role1: 'Massage Therapist', Role2: 'Receptionist', Role3: 'Aesthetician',
    Role4: 'Manicurist', Role5: 'Sauna Attendant', Role6: 'VIP Client',
    Role7: 'Nail Technician', Role8: 'Hair Stylist', Role9: 'Aromatherapist',
    Role10: 'Yoga Instructor', Role11: 'Personal Trainer', Role12: 'Nutritionist',
    Role13: 'Pedicurist', Role14: 'Gift Certificate Recipient Who\'s Never Been to a Spa', Role15: 'Man Dragged Here by Partner', Role16: 'First-Timer Who\'s Very Uncomfortable'
  },
  {
    Location: 'Embassy', set: 'classic',
    Role1: 'Ambassador', Role2: 'Consul', Role3: 'Security Officer',
    Role4: 'Translator', Role5: 'Visa Applicant', Role6: 'Intelligence Officer',
    Role7: 'Deputy Chief', Role8: 'Political Adviser', Role9: 'Press Attaché',
    Role10: 'Marine Guard', Role11: 'Diplomatic Courier', Role12: 'Cultural Attaché',
    Role13: 'Trade Representative', Role14: 'Journalist Staking It Out', Role15: 'Nervous Applicant Who Forgot Documents', Role16: 'Person Trying to Report a Stolen Passport'
  },
  {
    Location: 'Hospital', set: 'classic',
    Role1: 'Doctor', Role2: 'Nurse', Role3: 'Surgeon',
    Role4: 'Patient', Role5: 'Anesthesiologist', Role6: 'Emergency Physician',
    Role7: 'Paramedic', Role8: 'Radiologist', Role9: 'Pharmacist',
    Role10: 'Physical Therapist', Role11: 'Lab Technician', Role12: 'Orderly',
    Role13: 'Hypochondriac', Role14: 'Confused New Intern', Role15: 'Worried Parent in Waiting Room', Role16: 'Patient Who Self-Diagnosed on Google'
  },
  {
    Location: 'Hotel', set: 'classic',
    Role1: 'Concierge', Role2: 'Bellhop', Role3: 'Housekeeper',
    Role4: 'Front Desk Manager', Role5: 'Guest', Role6: 'Chef',
    Role7: 'Valet', Role8: 'Event Coordinator', Role9: 'Pool Attendant',
    Role10: 'Sommelier', Role11: 'Room Service Waiter', Role12: 'Head of Security',
    Role13: 'Maintenance Technician', Role14: 'VIP Guest', Role15: 'Person Checking In at 3am', Role16: 'Guest Who Left a 1-Star Review and Came Back Anyway'
  },
  {
    Location: 'Military Base', set: 'classic',
    Role1: 'General', Role2: 'Drill Sergeant', Role3: 'Soldier',
    Role4: 'Intelligence Officer', Role5: 'Mechanic', Role6: 'Cook',
    Role7: 'Sniper', Role8: 'Medic', Role9: 'Bomb Disposal Expert',
    Role10: 'Tank Commander', Role11: 'Military Police', Role12: 'Combat Pilot',
    Role13: 'Special Forces Operative', Role14: 'Base Commander', Role15: 'New Recruit on Day One', Role16: 'Soldier Counting Down the Days to Discharge'
  },
  {
    Location: 'Movie Studio', set: 'classic',
    Role1: 'Director', Role2: 'Lead Actor', Role3: 'Stunt Double',
    Role4: 'Cinematographer', Role5: 'Props Manager', Role6: 'Makeup Artist',
    Role7: 'Producer', Role8: 'Screenwriter', Role9: 'Sound Designer',
    Role10: 'Visual Effects Artist', Role11: 'Costume Designer', Role12: 'Casting Director',
    Role13: 'Gaffer', Role14: 'Script Supervisor', Role15: 'Film Editor', Role16: 'Actor Who Keeps Forgetting Lines'
  },
  {
    Location: 'Ocean Liner', set: 'classic',
    Role1: 'Captain', Role2: 'Navigator', Role3: 'Cruise Director',
    Role4: 'Passenger', Role5: 'Chef', Role6: 'Deckhand',
    Role7: 'First Officer', Role8: 'Entertainment Director', Role9: 'Purser',
    Role10: 'Casino Manager', Role11: 'Sommelier', Role12: 'Security Officer',
    Role13: 'Medical Officer', Role14: 'Engineer', Role15: 'Passenger Who\'s Seasick', Role16: 'Person Who Never Leaves the Buffet'
  },
  {
    Location: 'Passenger Train', set: 'classic',
    Role1: 'Conductor', Role2: 'Engineer', Role3: 'Ticket Inspector',
    Role4: 'Sleeping Car Attendant', Role5: 'Passenger', Role6: 'Stowaway',
    Role7: 'Station Master', Role8: 'Dining Car Chef', Role9: 'Porter',
    Role10: 'Rail Marshal', Role11: 'Train Dispatcher', Role12: 'Freight Supervisor',
    Role13: 'Snack Vendor', Role14: 'Rail Inspector', Role15: 'Person Who Missed Their Stop', Role16: 'Passenger Arguing About a Reserved Seat'
  },
  {
    Location: 'Pirate Ship', set: 'classic',
    Role1: 'Captain', Role2: 'First Mate', Role3: 'Navigator',
    Role4: 'Cannoneer', Role5: 'Cook', Role6: 'Prisoner',
    Role7: 'Boatswain', Role8: 'Lookout', Role9: 'Carpenter',
    Role10: 'Surgeon', Role11: 'Quartermaster', Role12: 'Deckhand',
    Role13: 'Gunner', Role14: 'Spy', Role15: 'Treasure Master', Role16: 'Cabin Boy'
  },
  {
    Location: 'Polar Station', set: 'classic',
    Role1: 'Expedition Leader', Role2: 'Climatologist', Role3: 'Meteorologist',
    Role4: 'Medic', Role5: 'Radio Operator', Role6: 'Dog Sled Driver',
    Role7: 'Glaciologist', Role8: 'Biologist', Role9: 'Engineer',
    Role10: 'Supply Officer', Role11: 'Ice Driller', Role12: 'Marine Biologist',
    Role13: 'Helicopter Pilot', Role14: 'Chef', Role15: 'Researcher Going Stir-Crazy', Role16: 'Person Who Lied About Tolerating Cold'
  },
  {
    Location: 'Police Station', set: 'classic',
    Role1: 'Police Chief', Role2: 'Detective', Role3: 'Patrol Officer',
    Role4: 'Forensic Analyst', Role5: 'Dispatcher', Role6: 'Suspect',
    Role7: 'Homicide Inspector', Role8: 'SWAT Commander', Role9: 'Undercover Agent',
    Role10: 'Crime Scene Technician', Role11: 'K9 Handler', Role12: 'Desk Sergeant',
    Role13: 'Evidence Clerk', Role14: 'Internal Affairs', Role15: 'Person Reporting a Missing Cat', Role16: 'Guy Disputing a Parking Ticket'
  },
  {
    Location: 'Restaurant', set: 'classic',
    Role1: 'Head Chef', Role2: 'Sous Chef', Role3: 'Waiter',
    Role4: 'Sommelier', Role5: 'Food Critic', Role6: 'Busboy',
    Role7: 'Pastry Chef', Role8: 'Host', Role9: 'Bartender',
    Role10: 'Manager', Role11: 'Line Cook', Role12: 'Dishwasher',
    Role13: 'Prep Cook', Role14: 'Mystery Diner', Role15: 'Table That\'s Been Waiting 45 Minutes', Role16: 'Person Who Sends Everything Back'
  },
  {
    Location: 'School', set: 'classic',
    Role1: 'Principal', Role2: 'Teacher', Role3: 'Student',
    Role4: 'Gym Coach', Role5: 'School Nurse', Role6: 'Janitor',
    Role7: 'Vice Principal', Role8: 'Librarian', Role9: 'Counselor',
    Role10: 'Art Teacher', Role11: 'Security Guard', Role12: 'Teacher\'s Pet',
    Role13: 'Class Clown', Role14: 'Exchange Student', Role15: 'Substitute Teacher Who Has Lost Control', Role16: 'Parent Causing Drama at the PTA Meeting'
  },
  {
    Location: 'Service Station', set: 'classic',
    Role1: 'Mechanic', Role2: 'Pump Attendant', Role3: 'Manager',
    Role4: 'Tow Truck Driver', Role5: 'Customer', Role6: 'Car Wash Worker',
    Role7: 'Tire Specialist', Role8: 'Auto Electrician', Role9: 'Oil Change Technician',
    Role10: 'Night Attendant', Role11: 'Apprentice Mechanic', Role12: 'Inspector',
    Role13: 'Detailer', Role14: 'Fuel Delivery Driver', Role15: 'Customer Who\'s Been Waiting 3 Hours', Role16: 'Person Who Ran Out of Gas Despite the Warnings'
  },
  {
    Location: 'Space Station', set: 'classic',
    Role1: 'Commander', Role2: 'Mission Specialist', Role3: 'Flight Engineer',
    Role4: 'Payload Specialist', Role5: 'Ground Control Liaison', Role6: 'Botanist',
    Role7: 'Flight Director', Role8: 'Robotics Expert', Role9: 'EVA Specialist',
    Role10: 'Medical Officer', Role11: 'Communications Officer', Role12: 'Research Scientist',
    Role13: 'Logistics Coordinator', Role14: 'Docking Pilot', Role15: 'Astronaut Terrified of Confined Spaces', Role16: 'Scientist Hoarding All the Snacks'
  },
  {
    Location: 'Submarine', set: 'classic',
    Role1: 'Captain', Role2: 'Sonar Operator', Role3: 'Torpedo Officer',
    Role4: 'Engineer', Role5: 'Cook', Role6: 'Navigator',
    Role7: 'Executive Officer', Role8: 'Weapons Officer', Role9: 'Medical Officer',
    Role10: 'Chief Petty Officer', Role11: 'Diving Officer', Role12: 'Communications Tech',
    Role13: 'Nuclear Reactor Operator', Role14: 'Lookout', Role15: 'New Recruit Who\'s Claustrophobic', Role16: 'Cook Complaining About the Kitchen Size'
  },
  {
    Location: 'Supermarket', set: 'classic',
    Role1: 'Store Manager', Role2: 'Cashier', Role3: 'Stock Boy',
    Role4: 'Butcher', Role5: 'Bakery Worker', Role6: 'Security Guard',
    Role7: 'Deli Worker', Role8: 'Produce Manager', Role9: 'Pharmacy Technician',
    Role10: 'Customer Service Rep', Role11: 'Loss Prevention Officer', Role12: 'Night Stocker',
    Role13: 'Fishmonger', Role14: 'Cart Collector', Role15: 'Person Arguing About an Expired Coupon', Role16: 'Shopper Who Came for One Thing and Left with a Full Cart'
  },
  {
    Location: 'University', set: 'classic',
    Role1: 'Professor', Role2: 'Graduate Student', Role3: 'Undergraduate',
    Role4: 'Dean', Role5: 'Librarian', Role6: 'Janitor',
    Role7: 'Registrar', Role8: 'Campus Security', Role9: 'Research Assistant',
    Role10: 'Athletics Coach', Role11: 'Academic Advisor', Role12: 'Lab Technician',
    Role13: 'Campus Tour Guide', Role14: 'IT Support', Role15: 'Student Who\'s Never Attended a Lecture', Role16: 'Professor Who Never Replies to Emails'
  },

  // ── Spyfall 2 ─────────────────────────────────────────────────────────────
  {
    Location: 'Amusement Park', set: 'spyfall2',
    Role1: 'Ride Operator', Role2: 'Park Manager', Role3: 'Food Vendor',
    Role4: 'Mascot', Role5: 'Thrill-Seeker', Role6: 'Maintenance Worker',
    Role7: 'Ticket Booth Worker', Role8: 'Security Guard', Role9: 'Game Booth Attendant',
    Role10: 'First Aid Attendant', Role11: 'Parade Performer', Role12: 'Balloon Artist',
    Role13: 'Carousel Operator', Role14: 'Lost & Found Officer', Role15: 'Person Who Got Stuck on a Ride', Role16: 'Child Crying Over the Height Requirement'
  },
  {
    Location: 'Art Museum', set: 'spyfall2',
    Role1: 'Curator', Role2: 'Art Restorer', Role3: 'Tour Guide',
    Role4: 'Security Guard', Role5: 'Patron', Role6: 'Struggling Artist',
    Role7: 'Gallery Director', Role8: 'Art Appraiser', Role9: 'Education Officer',
    Role10: 'Acquisitions Specialist', Role11: 'Conservationist', Role12: 'Auction Specialist',
    Role13: 'Intern', Role14: 'Gift Shop Manager', Role15: 'Person Who Doesn\'t Get Modern Art', Role16: 'Kid Who Accidentally Touched the Exhibit'
  },
  {
    Location: 'Candy Factory', set: 'spyfall2',
    Role1: 'Factory Manager', Role2: 'Chocolatier', Role3: 'Quality Taster',
    Role4: 'Machine Operator', Role5: 'Packaging Worker', Role6: 'Candy Inventor',
    Role7: 'Food Safety Inspector', Role8: 'Flavor Chemist', Role9: 'Marketing Manager',
    Role10: 'Supply Chain Manager', Role11: 'Shift Supervisor', Role12: 'Maintenance Engineer',
    Role13: 'Warehouse Worker', Role14: 'Transport Driver', Role15: 'Person Who\'s Eaten Way Too Much Today', Role16: 'Caramel Specialist'
  },
  {
    Location: 'Cat Show', set: 'spyfall2',
    Role1: 'Judge', Role2: 'Breeder', Role3: 'Groomer',
    Role4: 'Cat Owner', Role5: 'Spectator', Role6: 'Veterinarian',
    Role7: 'Show Organizer', Role8: 'Trophy Presenter', Role9: 'Photographer',
    Role10: 'Kitten Trainer', Role11: 'DNA Test Specialist', Role12: 'Cat Food Vendor',
    Role13: 'Commentator', Role14: 'Security', Role15: 'Extremely Competitive Cat Mom', Role16: 'Reluctant Owner Who Got Dragged Along'
  },
  {
    Location: 'Cemetery', set: 'spyfall2',
    Role1: 'Gravedigger', Role2: 'Funeral Director', Role3: 'Groundskeeper',
    Role4: 'Grieving Visitor', Role5: 'Ghost Tour Guide', Role6: 'Stone Carver',
    Role7: 'Mortician', Role8: 'Florist', Role9: 'Historian',
    Role10: 'Priest', Role11: 'Family Lawyer', Role12: 'Cemetery Manager',
    Role13: 'Coffin Maker', Role14: 'Security Guard', Role15: 'Goth Teen Who Just Hangs Out Here', Role16: 'Person Who Got Lost Looking for a Grave'
  },
  {
    Location: 'Coal Mine', set: 'spyfall2',
    Role1: 'Mine Foreman', Role2: 'Coal Miner', Role3: 'Safety Inspector',
    Role4: 'Explosives Expert', Role5: 'Canary Handler', Role6: 'Cart Pusher',
    Role7: 'Ventilation Engineer', Role8: 'Rock Driller', Role9: 'Hoist Operator',
    Role10: 'Geologist', Role11: 'Rescue Team Leader', Role12: 'Mine Surveyor',
    Role13: 'Coal Sorter', Role14: 'Mine Doctor', Role15: 'First Day Worker Who Already Regrets This', Role16: 'Miner Counting Days to Retirement'
  },
  {
    Location: 'Construction Site', set: 'spyfall2',
    Role1: 'Foreman', Role2: 'Crane Operator', Role3: 'Bricklayer',
    Role4: 'Electrician', Role5: 'Architect', Role6: 'Safety Inspector',
    Role7: 'Plumber', Role8: 'Welder', Role9: 'Site Engineer',
    Role10: 'Demolition Expert', Role11: 'Surveyor', Role12: 'Project Manager',
    Role13: 'Material Supplier', Role14: 'Concrete Mixer Operator', Role15: 'Worker on Phone the Entire Time', Role16: 'Guy Eating Lunch on a Beam 30 Stories Up'
  },
  {
    Location: 'Gaming Convention', set: 'spyfall2',
    Role1: 'Game Developer', Role2: 'Cosplayer', Role3: 'Tournament Referee',
    Role4: 'Merch Seller', Role5: 'Speed Runner', Role6: 'Casual Fan',
    Role7: 'Publisher Rep', Role8: 'Twitch Streamer', Role9: 'Voice Actor',
    Role10: 'Board Game Designer', Role11: 'Esports Coach', Role12: 'Convention Organizer',
    Role13: 'Artist Alley Creator', Role14: 'Media Journalist', Role15: 'Tournament Player Way Too Intense About This', Role16: 'Person in a Terrifyingly Detailed Costume'
  },
  {
    Location: 'Gas Station', set: 'spyfall2',
    Role1: 'Cashier', Role2: 'Mechanic', Role3: 'Manager',
    Role4: 'Trucker', Role5: 'Night Shift Attendant', Role6: 'Squeegee Kid',
    Role7: 'Car Wash Operator', Role8: 'Road Trip Traveler', Role9: 'Delivery Driver',
    Role10: 'Fuel Tanker Driver', Role11: 'Convenience Store Worker', Role12: 'Tire Repairman',
    Role13: 'Tow Truck Driver', Role14: 'Police Officer', Role15: 'Lost Tourist', Role16: 'Person Who Always Prepays Exact Change in Cash'
  },
  {
    Location: 'Harbor Docks', set: 'spyfall2',
    Role1: 'Harbormaster', Role2: 'Longshoreman', Role3: 'Customs Officer',
    Role4: 'Fisherman', Role5: 'Ferry Captain', Role6: 'Yacht Owner',
    Role7: 'Maritime Lawyer', Role8: 'Boat Mechanic', Role9: 'Port Security',
    Role10: 'Cargo Inspector', Role11: 'Sailing Instructor', Role12: 'Marine Biologist',
    Role13: 'Tugboat Captain', Role14: 'Naval Officer', Role15: 'Smuggler', Role16: 'Fisherman Who Never Catches Anything'
  },
  {
    Location: 'Ice Hockey Stadium', set: 'spyfall2',
    Role1: 'Goalie', Role2: 'Right Wing', Role3: 'Coach',
    Role4: 'Referee', Role5: 'Zamboni Driver', Role6: 'Die-Hard Fan',
    Role7: 'Team Captain', Role8: 'Defenseman', Role9: 'Equipment Manager',
    Role10: 'Sports Broadcaster', Role11: 'Stadium Security', Role12: 'Penalty Box Official',
    Role13: 'Physiotherapist', Role14: 'Scout', Role15: 'Fan Wearing the Wrong Team\'s Jersey', Role16: 'Person Here Just for the Nachos'
  },
  {
    Location: 'Jail', set: 'spyfall2',
    Role1: 'Warden', Role2: 'Guard', Role3: 'Prisoner',
    Role4: 'Lawyer', Role5: 'Chaplain', Role6: 'Parole Officer',
    Role7: 'Prison Doctor', Role8: 'Counselor', Role9: 'Corrections Officer',
    Role10: 'Undercover Cop', Role11: 'Gang Leader', Role12: 'Informant',
    Role13: 'Kitchen Worker', Role14: 'Prison Librarian', Role15: 'First-Timer Who\'s Absolutely Terrified', Role16: 'Lawyer Who Has Never Won a Case'
  },
  {
    Location: 'Jazz Club', set: 'spyfall2',
    Role1: 'Saxophone Player', Role2: 'Vocalist', Role3: 'Bartender',
    Role4: 'Club Owner', Role5: 'Jazz Critic', Role6: 'Regular Patron',
    Role7: 'Trumpet Player', Role8: 'Pianist', Role9: 'Drummer',
    Role10: 'Booking Agent', Role11: 'Sound Engineer', Role12: 'VIP Guest',
    Role13: 'Lighting Technician', Role14: 'Late-Night Cook', Role15: 'Person Who Came to the Wrong Bar', Role16: 'Someone Who Requested a Pop Song'
  },
  {
    Location: 'Library', set: 'spyfall2',
    Role1: 'Head Librarian', Role2: 'Archivist', Role3: 'Children\'s Librarian',
    Role4: 'IT Specialist', Role5: 'Bookworm', Role6: 'Quiet Rebel',
    Role7: 'Research Librarian', Role8: 'Volunteer', Role9: 'Rare Books Custodian',
    Role10: 'Interlibrary Loan Officer', Role11: 'Digital Resources Manager', Role12: 'Library Security',
    Role13: 'Local History Expert', Role14: 'Person Who Can\'t Find Their Book', Role15: 'Someone Who Keeps Getting Shushed', Role16: 'Person Here Just for the Air Conditioning'
  },
  {
    Location: 'Night Club', set: 'spyfall2',
    Role1: 'DJ', Role2: 'Bouncer', Role3: 'Bartender',
    Role4: 'VIP Guest', Role5: 'Promoter', Role6: 'Coat Check Attendant',
    Role7: 'Club Owner', Role8: 'Cocktail Waitress', Role9: 'Lighting Director',
    Role10: 'Limo Driver', Role11: 'Paparazzi', Role12: 'Underage Crasher',
    Role13: 'Social Media Influencer', Role14: 'Floor Manager', Role15: 'Person Who Came Alone and Regrets It', Role16: 'Someone Regretting Their Choice of Shoes'
  },
  {
    Location: 'Race Track', set: 'spyfall2',
    Role1: 'Race Car Driver', Role2: 'Pit Crew Chief', Role3: 'Race Engineer',
    Role4: 'Bookmaker', Role5: 'Commentator', Role6: 'Reckless Fan',
    Role7: 'Team Owner', Role8: 'Tire Specialist', Role9: 'Fueling Technician',
    Role10: 'Flagman', Role11: 'Track Marshal', Role12: 'Safety Car Driver',
    Role13: 'Sponsor Rep', Role14: 'Qualifying Official', Role15: 'Person Who Just Bet Their Savings', Role16: 'Driver Who Crashed on Lap One'
  },
  {
    Location: 'Retirement Home', set: 'spyfall2',
    Role1: 'Director', Role2: 'Nurse', Role3: 'Resident',
    Role4: 'Activities Coordinator', Role5: 'Visiting Grandchild', Role6: 'Physical Therapist',
    Role7: 'Social Worker', Role8: 'Chef', Role9: 'Night Supervisor',
    Role10: 'Occupational Therapist', Role11: 'Chaplain', Role12: 'Maintenance Worker',
    Role13: 'Laundry Staff', Role14: 'Weekend Volunteer', Role15: 'Resident Who Thinks It\'s Still 1965', Role16: 'Visiting Grandchild Who Came Out of Obligation'
  },
  {
    Location: 'Rock Concert', set: 'spyfall2',
    Role1: 'Lead Guitarist', Role2: 'Drummer', Role3: 'Tour Manager',
    Role4: 'Roadie', Role5: 'Groupie', Role6: 'Security Guard',
    Role7: 'Bass Player', Role8: 'Vocalist', Role9: 'Stage Manager',
    Role10: 'Lighting Tech', Role11: 'Sound Engineer', Role12: 'Merchandise Seller',
    Role13: 'Backstage Pass Holder', Role14: 'Music Journalist', Role15: 'Person Recording the Entire Concert on Their Phone', Role16: 'Guy Who\'s Too Tall Standing Right in Front'
  },
  {
    Location: 'Sightseeing Bus', set: 'spyfall2',
    Role1: 'Tour Guide', Role2: 'Bus Driver', Role3: 'Tourist',
    Role4: 'Local Historian', Role5: 'Pickpocket', Role6: 'Exchange Student',
    Role7: 'Travel Blogger', Role8: 'Guidebook Author', Role9: 'Sleepy Backpacker',
    Role10: 'Bus Mechanic', Role11: 'Corporate Tourist', Role12: 'Child on School Trip',
    Role13: 'Retired Traveler', Role14: 'Documentary Filmmaker', Role15: 'Tourist Who Asks Way Too Many Questions', Role16: 'Local Who Got on the Wrong Bus'
  },
  {
    Location: 'Stadium', set: 'spyfall2',
    Role1: 'Team Captain', Role2: 'Coach', Role3: 'Referee',
    Role4: 'Announcer', Role5: 'Hotdog Vendor', Role6: 'Die-Hard Fan',
    Role7: 'Sports Journalist', Role8: 'Team Mascot', Role9: 'Stadium Security',
    Role10: 'Ticket Scanner', Role11: 'Groundskeeper', Role12: 'Medical Staff',
    Role13: 'Talent Scout', Role14: 'Seat Usher', Role15: 'Fan Who Explains the Rules Wrong', Role16: 'Away Team Fan Who Sat in the Wrong Section'
  },
  {
    Location: 'Subway', set: 'spyfall2',
    Role1: 'Train Driver', Role2: 'Conductor', Role3: 'Busker',
    Role4: 'Commuter', Role5: 'Pickpocket', Role6: 'Station Manager',
    Role7: 'Ticket Inspector', Role8: 'Maintenance Worker', Role9: 'Platform Guard',
    Role10: 'Rush Hour Commuter', Role11: 'Tourist', Role12: 'Subway Artist',
    Role13: 'Lost Passenger', Role14: 'Transit Police', Role15: 'Person Eating a Full Hot Meal', Role16: 'Busker Who\'s Actually Pretty Bad'
  },
  {
    Location: 'The U.N.', set: 'spyfall2',
    Role1: 'Secretary-General', Role2: 'Ambassador', Role3: 'Interpreter',
    Role4: 'Security Officer', Role5: 'Journalist', Role6: 'Protester',
    Role7: 'Legal Counsel', Role8: 'Peacekeeping Commander', Role9: 'Human Rights Investigator',
    Role10: 'Head of State', Role11: 'Cultural Attaché', Role12: 'Communications Director',
    Role13: 'NGO Representative', Role14: 'Negotiator', Role15: 'Interpreter Who\'s Struggling', Role16: 'Diplomat Who Fell Asleep'
  },
  {
    Location: 'Vineyard', set: 'spyfall2',
    Role1: 'Winemaker', Role2: 'Sommelier', Role3: 'Harvest Worker',
    Role4: 'Tour Guide', Role5: 'Wine Critic', Role6: 'Cellar Master',
    Role7: 'Vineyard Owner', Role8: 'Grape Sorter', Role9: 'Wine Chemist',
    Role10: 'Estate Manager', Role11: 'Barrel Maker', Role12: 'Wine Educator',
    Role13: 'Restaurant Partner', Role14: 'Harvest Festival Coordinator', Role15: 'Tourist Here Purely for the Free Samples', Role16: 'Person Who Bought Way Too Many Bottles'
  },
  {
    Location: 'Wedding', set: 'spyfall2',
    Role1: 'Bride', Role2: 'Groom', Role3: 'Best Man',
    Role4: 'Maid of Honor', Role5: 'Wedding Planner', Role6: 'Officiant',
    Role7: 'Flower Girl', Role8: 'Ring Bearer', Role9: 'Catering Manager',
    Role10: 'Wedding Photographer', Role11: 'DJ', Role12: 'Florist',
    Role13: 'Drunk Uncle', Role14: 'Ex Who Was Accidentally Invited', Role15: 'Guest Who Only Came for the Open Bar', Role16: 'Crying Mother of the Bride'
  },
  {
    Location: 'Zoo', set: 'spyfall2',
    Role1: 'Zookeeper', Role2: 'Veterinarian', Role3: 'Tour Guide',
    Role4: 'Gift Shop Worker', Role5: 'Conservation Expert', Role6: 'School Child',
    Role7: 'Animal Nutritionist', Role8: 'Zoo Director', Role9: 'Education Officer',
    Role10: 'Reptile Specialist', Role11: 'Primate Handler', Role12: 'Safari Photographer',
    Role13: 'Volunteer', Role14: 'Zoo Architect', Role15: 'Child Trying to Feed the Animals Everything', Role16: 'Person Here Only for the Penguins'
  },

  // ── Anime ─────────────────────────────────────────────────────────────────────
  { Location: 'Attack on Titan', set: 'anime',
    Role1: 'Eren Yeager', Role2: 'Mikasa Ackerman', Role3: 'Armin Arlert',
    Role4: 'Levi Ackerman', Role5: 'Hange Zoë', Role6: 'Erwin Smith',
    Role7: 'Sasha Blouse', Role8: 'Connie Springer', Role9: 'Historia Reiss', Role10: 'Reiner Braun' },
  { Location: 'Naruto', set: 'anime',
    Role1: 'Naruto Uzumaki', Role2: 'Sasuke Uchiha', Role3: 'Sakura Haruno',
    Role4: 'Kakashi Hatake', Role5: 'Itachi Uchiha', Role6: 'Gaara',
    Role7: 'Rock Lee', Role8: 'Neji Hyuga', Role9: 'Hinata Hyuga', Role10: 'Jiraiya' },
  { Location: 'One Piece', set: 'anime',
    Role1: 'Monkey D. Luffy', Role2: 'Roronoa Zoro', Role3: 'Nami',
    Role4: 'Usopp', Role5: 'Sanji', Role6: 'Tony Tony Chopper',
    Role7: 'Nico Robin', Role8: 'Franky', Role9: 'Brook', Role10: 'Jinbe' },
  { Location: 'Dragon Ball Z', set: 'anime',
    Role1: 'Son Goku', Role2: 'Vegeta', Role3: 'Gohan',
    Role4: 'Piccolo', Role5: 'Frieza', Role6: 'Cell',
    Role7: 'Future Trunks', Role8: 'Krillin', Role9: 'Bulma', Role10: 'Android 18' },
  { Location: 'Bleach', set: 'anime',
    Role1: 'Ichigo Kurosaki', Role2: 'Rukia Kuchiki', Role3: 'Orihime Inoue',
    Role4: 'Uryū Ishida', Role5: 'Byakuya Kuchiki', Role6: 'Renji Abarai',
    Role7: 'Sōsuke Aizen', Role8: 'Kisuke Urahara', Role9: 'Gin Ichimaru', Role10: 'Tōshirō Hitsugaya' },
  { Location: 'Death Note', set: 'anime',
    Role1: 'Light Yagami', Role2: 'L Lawliet', Role3: 'Ryuk',
    Role4: 'Misa Amane', Role5: 'Near', Role6: 'Mello',
    Role7: 'Sōichirō Yagami', Role8: 'Teru Mikami', Role9: 'Touta Matsuda', Role10: 'Rem' },
  { Location: 'Fullmetal Alchemist: Brotherhood', set: 'anime',
    Role1: 'Edward Elric', Role2: 'Alphonse Elric', Role3: 'Winry Rockbell',
    Role4: 'Roy Mustang', Role5: 'Riza Hawkeye', Role6: 'Scar',
    Role7: 'Ling Yao', Role8: 'Greedling', Role9: 'Olivier Armstrong', Role10: 'Van Hohenheim' },
  { Location: 'My Hero Academia', set: 'anime',
    Role1: 'Izuku Midoriya', Role2: 'Katsuki Bakugo', Role3: 'Ochaco Uraraka',
    Role4: 'Shoto Todoroki', Role5: 'All Might', Role6: 'Shota Aizawa',
    Role7: 'Endeavor', Role8: 'Tenya Iida', Role9: 'Tsuyu Asui', Role10: 'Eijiro Kirishima' },
  { Location: 'Demon Slayer', set: 'anime',
    Role1: 'Tanjiro Kamado', Role2: 'Nezuko Kamado', Role3: 'Zenitsu Agatsuma',
    Role4: 'Inosuke Hashibira', Role5: 'Kyojuro Rengoku', Role6: 'Tengen Uzui',
    Role7: 'Gyomei Himejima', Role8: 'Muzan Kibutsuji', Role9: 'Shinobu Kocho', Role10: 'Sanemi Shinazugawa' },
  { Location: 'Hunter x Hunter', set: 'anime',
    Role1: 'Gon Freecss', Role2: 'Killua Zoldyck', Role3: 'Kurapika',
    Role4: 'Leorio Paradinight', Role5: 'Hisoka Morow', Role6: 'Chrollo Lucilfer',
    Role7: 'Meruem', Role8: 'Komugi', Role9: 'Illumi Zoldyck', Role10: 'Neferpitou' },
  { Location: 'Sword Art Online', set: 'anime',
    Role1: 'Kirito', Role2: 'Asuna', Role3: 'Sinon',
    Role4: 'Klein', Role5: 'Agil', Role6: 'Eugeo',
    Role7: 'Alice', Role8: 'Leafa', Role9: 'Silica', Role10: 'Lisbeth' },
  { Location: 'Tokyo Ghoul', set: 'anime',
    Role1: 'Ken Kaneki', Role2: 'Touka Kirishima', Role3: 'Rize Kamishiro',
    Role4: 'Hideyoshi Nagachika', Role5: 'Koutarou Amon', Role6: 'Juuzou Suzuya',
    Role7: 'Kishou Arima', Role8: 'Hinami Fueguchi', Role9: 'Shu Tsukiyama', Role10: 'Yoshimura' },
  { Location: 'Fairy Tail', set: 'anime',
    Role1: 'Natsu Dragneel', Role2: 'Lucy Heartfilia', Role3: 'Erza Scarlet',
    Role4: 'Gray Fullbuster', Role5: 'Happy', Role6: 'Mavis Vermillion',
    Role7: 'Zeref Dragneel', Role8: 'Mirajane Strauss', Role9: 'Gajeel Redfox', Role10: 'Wendy Marvell' },
  { Location: 'One Punch Man', set: 'anime',
    Role1: 'Saitama', Role2: 'Genos', Role3: 'Tatsumaki',
    Role4: 'Bang', Role5: 'Atomic Samurai', Role6: 'King',
    Role7: 'Zombieman', Role8: 'Metal Bat', Role9: 'Flashy Flash', Role10: 'Garou' },
  { Location: 'Jujutsu Kaisen', set: 'anime',
    Role1: 'Yuji Itadori', Role2: 'Satoru Gojo', Role3: 'Megumi Fushiguro',
    Role4: 'Nobara Kugisaki', Role5: 'Nanami Kento', Role6: 'Ryomen Sukuna',
    Role7: 'Yuta Okkotsu', Role8: 'Aoi Todo', Role9: 'Toge Inumaki', Role10: 'Choso' },
  { Location: 'Chainsaw Man', set: 'anime',
    Role1: 'Denji', Role2: 'Power', Role3: 'Makima',
    Role4: 'Aki Hayakawa', Role5: 'Kobeni Higashiyama', Role6: 'Himeno',
    Role7: 'Kishibe', Role8: 'Quanxi', Role9: 'Reze', Role10: 'Beam' },
  { Location: 'Re:Zero', set: 'anime',
    Role1: 'Subaru Natsuki', Role2: 'Emilia', Role3: 'Rem',
    Role4: 'Ram', Role5: 'Beatrice', Role6: 'Roswaal L. Mathers',
    Role7: 'Echidna', Role8: 'Garfiel Tinsel', Role9: 'Otto Suwen', Role10: 'Frederica Baumann' },
  { Location: 'Cowboy Bebop', set: 'anime',
    Role1: 'Spike Spiegel', Role2: 'Faye Valentine', Role3: 'Jet Black',
    Role4: 'Edward Wong', Role5: 'Ein', Role6: 'Vicious',
    Role7: 'Julia', Role8: 'Gren', Role9: 'Mad Pierrot', Role10: 'Andy' },
  { Location: 'Steins;Gate', set: 'anime',
    Role1: 'Rintaro Okabe', Role2: 'Kurisu Makise', Role3: 'Itaru Hashida',
    Role4: 'Mayuri Shiina', Role5: 'Suzuha Amane', Role6: 'Moeka Kiryu',
    Role7: 'Ruka Urushibara', Role8: 'Yuugo Tennouji', Role9: 'Faris NyanNyan', Role10: 'Yuki Amane' },
  { Location: 'Neon Genesis Evangelion', set: 'anime',
    Role1: 'Shinji Ikari', Role2: 'Rei Ayanami', Role3: 'Asuka Langley Soryu',
    Role4: 'Misato Katsuragi', Role5: 'Gendo Ikari', Role6: 'Kaworu Nagisa',
    Role7: 'Ritsuko Akagi', Role8: 'Ryoji Kaji', Role9: 'Yui Ikari', Role10: 'Pen Pen' },
  { Location: 'Code Geass', set: 'anime',
    Role1: 'Lelouch vi Britannia', Role2: 'Suzaku Kururugi', Role3: 'C.C.',
    Role4: 'Kallen Stadtfeld', Role5: 'Nunnally vi Britannia', Role6: 'Jeremiah Gottwald',
    Role7: 'Rivalz Cardemonde', Role8: 'Shirley Fenette', Role9: 'Schneizel el Britannia', Role10: 'Rolo Lamperouge' },
  { Location: 'Mob Psycho 100', set: 'anime',
    Role1: 'Shigeo Kageyama', Role2: 'Arataka Reigen', Role3: 'Dimple',
    Role4: 'Ritsu Kageyama', Role5: 'Teruki Hanazawa', Role6: 'Tome Kurata',
    Role7: 'Sho Suzuki', Role8: 'Katsuya Serizawa', Role9: 'Musashi Gouda', Role10: 'Minori Asagiri' },
  { Location: 'Haikyuu', set: 'anime',
    Role1: 'Shōyō Hinata', Role2: 'Tobio Kageyama', Role3: 'Kei Tsukishima',
    Role4: 'Tadashi Yamaguchi', Role5: 'Daichi Sawamura', Role6: 'Kōshi Sugawara',
    Role7: 'Asahi Azumane', Role8: 'Nishinoya Yū', Role9: 'Ryūnosuke Tanaka', Role10: 'Kōtarō Bokuto' },
  { Location: 'Berserk', set: 'anime',
    Role1: 'Guts', Role2: 'Griffith', Role3: 'Casca',
    Role4: 'Puck', Role5: 'Farnese de Vandimion', Role6: 'Serpico',
    Role7: 'Isidro', Role8: 'Schierke', Role9: 'Skull Knight', Role10: 'Nosferatu Zodd' },
  { Location: 'Spy x Family', set: 'anime',
    Role1: 'Loid Forger', Role2: 'Yor Forger', Role3: 'Anya Forger',
    Role4: 'Bond Forger', Role5: 'Franky Franklin', Role6: 'Sylvia Sherwood',
    Role7: 'Nightfall', Role8: 'Yuri Briar', Role9: 'Damian Desmond', Role10: 'Becky Blackbell' },
  { Location: 'Black Clover', set: 'anime',
    Role1: 'Asta', Role2: 'Yuno', Role3: 'Noelle Silva',
    Role4: 'Captain Yami Sukehiro', Role5: 'Julius Novachrono', Role6: 'Fuegoleon Vermillion',
    Role7: 'Rill Boismortier', Role8: 'Charlotte Roselei', Role9: 'Jack the Ripper', Role10: 'Mereoleona Vermillion' },
  { Location: 'Vinland Saga', set: 'anime',
    Role1: 'Thorfinn', Role2: 'Askeladd', Role3: 'Bjorn',
    Role4: 'Thorkell', Role5: 'Prince Canute', Role6: 'Leif Erikson',
    Role7: 'Floki', Role8: 'Einar', Role9: 'Anne', Role10: 'Gudrid' },
  { Location: 'Blue Lock', set: 'anime',
    Role1: 'Yoichi Isagi', Role2: 'Meguru Bachira', Role3: 'Seishiro Nagi',
    Role4: 'Reo Mikage', Role5: 'Rin Itoshi', Role6: 'Sae Itoshi',
    Role7: 'Ryusei Shidou', Role8: 'Chigiri Hyoma', Role9: 'Aryu Jyubei', Role10: 'Michael Kaiser' },
  { Location: 'Sailor Moon', set: 'anime',
    Role1: 'Sailor Moon', Role2: 'Sailor Mercury', Role3: 'Sailor Mars',
    Role4: 'Sailor Jupiter', Role5: 'Sailor Venus', Role6: 'Tuxedo Mask',
    Role7: 'Chibiusa', Role8: 'Luna', Role9: 'Artemis', Role10: 'Queen Beryl' },
  { Location: 'Overlord', set: 'anime',
    Role1: 'Ainz Ooal Gown', Role2: 'Albedo', Role3: 'Shalltear Bloodfallen',
    Role4: 'Demiurge', Role5: 'Sebas Tian', Role6: 'Aura Bella Fiora',
    Role7: 'Mare Bello Fiore', Role8: 'Cocytus', Role9: 'Narberal Gamma', Role10: 'Pandora\'s Actor' },

  // ── League of Legends ─────────────────────────────────────────────────────────
  { Location: 'Jinx', set: 'lol',
    Role1: 'Marksman', Role2: 'AD Carry', Role3: 'Zaun Criminal',
    Role4: 'Loose Cannon', Role5: 'Mini-Gun Enthusiast', Role6: 'Fishbones Rocket User',
    Role7: 'Chaos Spreader', Role8: 'Arcane Character', Role9: 'Vi\'s Sister', Role10: 'Bounty Target' },
  { Location: 'Yasuo', set: 'lol',
    Role1: 'Midlaner', Role2: 'Wind Swordsman', Role3: 'Unforgiven Wanderer',
    Role4: 'Windwall Creator', Role5: 'Tornado Caster', Role6: 'Ionian Exile',
    Role7: 'Last Breath Finisher', Role8: 'Dual-Wielder', Role9: 'Hasagi Screamer', Role10: 'Yone\'s Brother' },
  { Location: 'Thresh', set: 'lol',
    Role1: 'Support', Role2: 'Chain Warden', Role3: 'Lantern Holder',
    Role4: 'Soul Collector', Role5: 'Shadow Isles Resident', Role6: 'Flay Expert',
    Role7: 'Death Sentence Hook', Role8: 'Box Creator', Role9: 'Spirit Tormentor', Role10: 'Blitzcrank\'s Rival' },
  { Location: 'Zed', set: 'lol',
    Role1: 'Assassin', Role2: 'Shadow Master', Role3: 'Death Mark User',
    Role4: 'Living Shadow Caster', Role5: 'League of Shadows Leader', Role6: 'Shen\'s Enemy',
    Role7: 'Energy User', Role8: 'Shuriken Thrower', Role9: 'Armor-Penetrator', Role10: 'Ult Predator' },
  { Location: 'Lee Sin', set: 'lol',
    Role1: 'Jungler', Role2: 'Blind Monk', Role3: 'Sonic Wave Caster',
    Role4: 'Dragon\'s Rage Kicker', Role5: 'Ward Hopper', Role6: 'Safeguard Diver',
    Role7: 'Tempest Caster', Role8: 'Insec Mechanic Master', Role9: 'Mobile Fighter', Role10: 'Energy User' },
  { Location: 'Vayne', set: 'lol',
    Role1: 'Marksman', Role2: 'Night Hunter', Role3: 'Silver Bolt User',
    Role4: 'Condemn Knocker', Role5: 'Tumble Shooter', Role6: 'Monster Hunter',
    Role7: 'AD Carry', Role8: 'Final Hour Activator', Role9: 'Darkness Fighter', Role10: 'Tank Shredder' },
  { Location: 'Ezreal', set: 'lol',
    Role1: 'Marksman', Role2: 'Prodigal Explorer', Role3: 'Mystic Shot Caster',
    Role4: 'Arcane Shift Dasher', Role5: 'Trueshot Barrage User', Role6: 'Piltover Explorer',
    Role7: 'Bracelet Wearer', Role8: 'Skillshot Reliant', Role9: 'Tryndamere\'s Bane', Role10: 'Blink Shooter' },
  { Location: 'Ahri', set: 'lol',
    Role1: 'Mage Assassin', Role2: 'Nine-Tailed Fox', Role3: 'Orb of Deception Caster',
    Role4: 'Charm User', Role5: 'Spirit Rush Dasher', Role6: 'Foxfire Wielder',
    Role7: 'Essence Thief', Role8: 'Vastaya', Role9: 'Life-Stealer', Role10: 'Triple Dash Expert' },
  { Location: 'Lux', set: 'lol',
    Role1: 'Mage', Role2: 'Support', Role3: 'Light Magic User',
    Role4: 'Final Spark Laser', Role5: 'Lucent Singularity', Role6: 'Snare Caster',
    Role7: 'Demacian Princess', Role8: 'Prismatic Barrier', Role9: 'Long-Range Poker', Role10: 'Illumination Passive' },
  { Location: 'Jhin', set: 'lol',
    Role1: 'Marksman', Role2: 'The Virtuoso', Role3: 'Four-Shot Revolver',
    Role4: 'Curtain Call Sniper', Role5: 'Lotus Trap Placer', Role6: 'Artistic Killer',
    Role7: 'Four Obsessed', Role8: 'Theatrical Assassin', Role9: 'Golden Road', Role10: 'Whisper Wielder' },
  { Location: 'Kai\'Sa', set: 'lol',
    Role1: 'Marksman', Role2: 'Daughter of the Void', Role3: 'Second Skin Armor',
    Role4: 'Killer Instinct Dasher', Role5: 'Icathian Rain Caster', Role6: 'Living Weapon',
    Role7: 'Void Survivor', Role8: 'AD Carry', Role9: 'Adaptive Shooter', Role10: 'Void Corruption' },
  { Location: 'Ekko', set: 'lol',
    Role1: 'Assassin', Role2: 'Boy Who Shattered Time', Role3: 'Chronobreak Recall',
    Role4: 'Time Winder Caster', Role5: 'Phase Dive Dasher', Role6: 'Zaun Street Kid',
    Role7: 'Parallel Convergence', Role8: 'Time Manipulator', Role9: 'Z-Drive Resonance', Role10: 'Arcane Character' },
  { Location: 'Vi', set: 'lol',
    Role1: 'Fighter', Role2: 'Piltover Enforcer', Role3: 'Vault Breaker',
    Role4: 'Denting Blows', Role5: 'Assault and Battery Ult', Role6: 'Excessive Force',
    Role7: 'Jinx\'s Sister', Role8: 'Punch Gauntlets', Role9: 'Caitlyn\'s Partner', Role10: 'Riot Puncher' },
  { Location: 'Draven', set: 'lol',
    Role1: 'Marksman', Role2: 'Glorious Executioner', Role3: 'Spinning Axe Juggler',
    Role4: 'League of Draven', Role5: 'Blood Rush Dasher', Role6: 'Stand Aside Caster',
    Role7: 'Whirling Death Global Ult', Role8: 'Noxian Executioner', Role9: 'Adoration Stacker', Role10: 'Ego Fighter' },
  { Location: 'Miss Fortune', set: 'lol',
    Role1: 'Marksman', Role2: 'Bounty Hunter', Role3: 'Bullet Time Ult',
    Role4: 'Double Up Caster', Role5: 'Strut Passive', Role6: 'Make It Rain',
    Role7: 'Love Tap Passive', Role8: 'Bilgewater Hunter', Role9: 'Dual Pistol Wielder', Role10: 'Gangplank\'s Enemy' },
  { Location: 'Caitlyn', set: 'lol',
    Role1: 'Marksman', Role2: 'Sheriff of Piltover', Role3: 'Headshot Passive',
    Role4: 'Yordle Snap Trap', Role5: '90 Caliber Net', Role6: 'Ace in the Hole Sniper',
    Role7: 'Long-Range Sniper', Role8: 'Hat Wearer', Role9: 'Vi\'s Partner', Role10: 'Arcane Character' },
  { Location: 'Akali', set: 'lol',
    Role1: 'Assassin', Role2: 'Rogue Assassin', Role3: 'Shuriken Flip',
    Role4: 'Five Point Strike', Role5: 'Twilight Shroud User', Role6: 'Perfect Execution',
    Role7: 'Kinkou Exile', Role8: 'Smoke Shroud', Role9: 'Energy User', Role10: 'K/DA Member' },
  { Location: 'Katarina', set: 'lol',
    Role1: 'Assassin', Role2: 'Sinister Blade', Role3: 'Preparation Passive',
    Role4: 'Bouncing Blade', Role5: 'Death Lotus Ult', Role6: 'Shunpo Dasher',
    Role7: 'Reset Mechanic', Role8: 'Noxian Assassin', Role9: 'Dagger Juggler', Role10: 'Garen\'s Nemesis' },
  { Location: 'Darius', set: 'lol',
    Role1: 'Fighter', Role2: 'Hand of Noxus', Role3: 'Hemorrhage Stack',
    Role4: 'Decimate Spin', Role5: 'Crippling Strike', Role6: 'Apprehend Pull',
    Role7: 'Noxian Guillotine', Role8: 'Noxian General', Role9: 'Bleed Stacker', Role10: 'Garen\'s Rival' },
  { Location: 'Garen', set: 'lol',
    Role1: 'Fighter', Role2: 'Might of Demacia', Role3: 'Decisive Strike',
    Role4: 'Courage Shield', Role5: 'Judgment Spin', Role6: 'Demacian Justice Ult',
    Role7: 'Demacian Soldier', Role8: 'Lux\'s Brother', Role9: 'Silence User', Role10: 'Spin to Win' },
  { Location: 'Teemo', set: 'lol',
    Role1: 'Marksman', Role2: 'Swift Scout', Role3: 'Toxic Shot Passive',
    Role4: 'Guerrilla Warfare Invisible', Role5: 'Noxious Trap Mushroom', Role6: 'Move Quick',
    Role7: 'Blinding Dart', Role8: 'Yordle Scout', Role9: 'Bandle City Native', Role10: 'Most Hated Champion' },
  { Location: 'Lucian', set: 'lol',
    Role1: 'Marksman', Role2: 'The Purifier', Role3: 'Lightslinger Passive',
    Role4: 'Ardent Blaze', Role5: 'Relentless Pursuit Dash', Role6: 'The Culling Ult',
    Role7: 'Double-Shot', Role8: 'Senna\'s Husband', Role9: 'Holy Light Magic', Role10: 'Demon Hunter' },
  { Location: 'Nami', set: 'lol',
    Role1: 'Support', Role2: 'The Tidecaller', Role3: 'Aqua Prison Bubble',
    Role4: 'Ebb and Flow Healer', Role5: 'Tidal Wave Ult', Role6: 'Tidecaller\'s Blessing',
    Role7: 'Ocean Mermaid', Role8: 'CC Chain Support', Role9: 'Buff Provider', Role10: 'Surf\'s Up' },
  { Location: 'Riven', set: 'lol',
    Role1: 'Fighter', Role2: 'The Exile', Role3: 'Broken Wings Combo',
    Role4: 'Ki Burst Stun', Role5: 'Valor Shield', Role6: 'Blade of the Exile Ult',
    Role7: 'Broken Sword User', Role8: 'Noxian Exile', Role9: 'Wind Slash', Role10: 'Combo Chainer' },
  { Location: 'Pyke', set: 'lol',
    Role1: 'Support Assassin', Role2: 'Bloodharbor Ripper', Role3: 'Bone Skewer Hook',
    Role4: 'Ghostwater Dive', Role5: 'Phantom Undertow Stun', Role6: 'Death from Below Ult',
    Role7: 'Gold Sharer', Role8: 'Ghostly Assassin', Role9: 'Drowned Man', Role10: 'Bilgewater Ghost' },
  { Location: 'Malphite', set: 'lol',
    Role1: 'Tank', Role2: 'Shard of the Monolith', Role3: 'Ground Slam',
    Role4: 'Brutal Strikes', Role5: 'Seismic Shard', Role6: 'Unstoppable Force Ult',
    Role7: 'Rock Solid Passive', Role8: 'Stone Golem', Role9: 'Ultimate Initiator', Role10: 'Armor Stacker' },
  { Location: 'Sett', set: 'lol',
    Role1: 'Fighter', Role2: 'The Boss', Role3: 'Pit Grit Passive',
    Role4: 'Facebreaker', Role5: 'Show Stopper Ult', Role6: 'Knuckle Down',
    Role7: 'Haymaker', Role8: 'Ionian Fighter', Role9: 'Fighting Pit Boss', Role10: 'Brute Force' },
  { Location: 'Yone', set: 'lol',
    Role1: 'Assassin', Role2: 'The Unforgotten', Role3: 'Mortal Steel',
    Role4: 'Spirit Cleave', Role5: 'Soul Unbound', Role6: 'Fate Sealed Ult',
    Role7: 'Azakana Hunter', Role8: 'Yasuo\'s Brother', Role9: 'Dual Swords', Role10: 'Spirit Form' },
  { Location: 'Sylas', set: 'lol',
    Role1: 'Mage Assassin', Role2: 'The Unshackled', Role3: 'Chain Lash',
    Role4: 'Kingslayer Heal', Role5: 'Abscond/Abduct Dash', Role6: 'Hijack Ult Stealer',
    Role7: 'Demacian Criminal', Role8: 'Magic Absorber', Role9: 'Petricite Chains', Role10: 'Ultimate Thief' },

  // ── Movies ────────────────────────────────────────────────────────────────────
  { Location: 'The Avengers', set: 'movies',
    Role1: 'Tony Stark', Role2: 'Steve Rogers', Role3: 'Thor',
    Role4: 'Natasha Romanoff', Role5: 'Clint Barton', Role6: 'Bruce Banner',
    Role7: 'Nick Fury', Role8: 'Phil Coulson', Role9: 'Loki', Role10: 'Maria Hill' },
  { Location: 'The Dark Knight', set: 'movies',
    Role1: 'Batman', Role2: 'The Joker', Role3: 'Harvey Dent',
    Role4: 'Alfred Pennyworth', Role5: 'Commissioner Gordon', Role6: 'Rachel Dawes',
    Role7: 'Lucius Fox', Role8: 'Ra\'s al Ghul', Role9: 'Scarecrow', Role10: 'Detective Ramirez' },
  { Location: 'The Godfather', set: 'movies',
    Role1: 'Michael Corleone', Role2: 'Vito Corleone', Role3: 'Tom Hagen',
    Role4: 'Sonny Corleone', Role5: 'Fredo Corleone', Role6: 'Kay Adams',
    Role7: 'Carlo Rizzi', Role8: 'Luca Brasi', Role9: 'Peter Clemenza', Role10: 'Sal Tessio' },
  { Location: 'Inception', set: 'movies',
    Role1: 'Dom Cobb', Role2: 'Arthur', Role3: 'Ariadne',
    Role4: 'Eames', Role5: 'Yusuf', Role6: 'Saito',
    Role7: 'Robert Fischer', Role8: 'Mal Cobb', Role9: 'Miles', Role10: 'Nash' },
  { Location: 'Interstellar', set: 'movies',
    Role1: 'Cooper', Role2: 'Murph', Role3: 'Amelia Brand',
    Role4: 'TARS', Role5: 'Romilly', Role6: 'Dr. Mann',
    Role7: 'Doyle', Role8: 'Young Murph', Role9: 'Donald', Role10: 'Tom Cooper' },
  { Location: 'Titanic', set: 'movies',
    Role1: 'Jack Dawson', Role2: 'Rose DeWitt Bukater', Role3: 'Captain Smith',
    Role4: 'Cal Hockley', Role5: 'Fabrizio', Role6: 'Molly Brown',
    Role7: 'Thomas Andrews', Role8: 'Officer Murdoch', Role9: 'Ruth DeWitt', Role10: 'Spicer Lovejoy' },
  { Location: 'Star Wars: A New Hope', set: 'movies',
    Role1: 'Luke Skywalker', Role2: 'Darth Vader', Role3: 'Princess Leia',
    Role4: 'Han Solo', Role5: 'Chewbacca', Role6: 'Obi-Wan Kenobi',
    Role7: 'C-3PO', Role8: 'R2-D2', Role9: 'Grand Moff Tarkin', Role10: 'Greedo' },
  { Location: 'The Matrix', set: 'movies',
    Role1: 'Neo', Role2: 'Morpheus', Role3: 'Trinity',
    Role4: 'Agent Smith', Role5: 'The Oracle', Role6: 'Tank',
    Role7: 'Switch', Role8: 'Apoc', Role9: 'Mouse', Role10: 'Cypher' },
  { Location: 'Pulp Fiction', set: 'movies',
    Role1: 'Vincent Vega', Role2: 'Jules Winnfield', Role3: 'Mia Wallace',
    Role4: 'Butch Coolidge', Role5: 'Marsellus Wallace', Role6: 'The Gimp',
    Role7: 'Winston Wolfe', Role8: 'Honey Bunny', Role9: 'Pumpkin', Role10: 'Lance' },
  { Location: 'The Shawshank Redemption', set: 'movies',
    Role1: 'Andy Dufresne', Role2: 'Red', Role3: 'Warden Norton',
    Role4: 'Brooks Hatlen', Role5: 'Tommy', Role6: 'Heywood',
    Role7: 'Floyd', Role8: 'Byron Hadley', Role9: 'Bogs Diamond', Role10: 'Captain Hadley' },
  { Location: 'Harry Potter', set: 'movies',
    Role1: 'Harry Potter', Role2: 'Hermione Granger', Role3: 'Ron Weasley',
    Role4: 'Albus Dumbledore', Role5: 'Severus Snape', Role6: 'Draco Malfoy',
    Role7: 'Hagrid', Role8: 'Voldemort', Role9: 'Neville Longbottom', Role10: 'Professor McGonagall' },
  { Location: 'The Lord of the Rings', set: 'movies',
    Role1: 'Frodo Baggins', Role2: 'Gandalf', Role3: 'Samwise Gamgee',
    Role4: 'Aragorn', Role5: 'Legolas', Role6: 'Gimli',
    Role7: 'Boromir', Role8: 'Merry', Role9: 'Pippin', Role10: 'Saruman' },
  { Location: 'Jurassic Park', set: 'movies',
    Role1: 'Dr. Alan Grant', Role2: 'Dr. Ellie Sattler', Role3: 'Dr. Ian Malcolm',
    Role4: 'John Hammond', Role5: 'Lex Murphy', Role6: 'Tim Murphy',
    Role7: 'Dennis Nedry', Role8: 'Ray Arnold', Role9: 'Robert Muldoon', Role10: 'Henry Wu' },
  { Location: 'The Lion King', set: 'movies',
    Role1: 'Simba', Role2: 'Mufasa', Role3: 'Nala',
    Role4: 'Scar', Role5: 'Timon', Role6: 'Pumbaa',
    Role7: 'Rafiki', Role8: 'Zazu', Role9: 'Sarabi', Role10: 'Shenzi' },
  { Location: 'Gladiator', set: 'movies',
    Role1: 'Maximus Decimus Meridius', Role2: 'Emperor Commodus', Role3: 'Lucilla',
    Role4: 'Proximo', Role5: 'Juba', Role6: 'Marcus Aurelius',
    Role7: 'Quintus', Role8: 'Tigris of Gaul', Role9: 'Gracchus', Role10: 'Hagen' },
  { Location: 'Fight Club', set: 'movies',
    Role1: 'The Narrator', Role2: 'Tyler Durden', Role3: 'Marla Singer',
    Role4: 'Bob', Role5: 'Angel Face', Role6: 'Richard Chesler',
    Role7: 'The Mechanic', Role8: 'Lou', Role9: 'Ricky', Role10: 'Detective Stern' },
  { Location: 'Forrest Gump', set: 'movies',
    Role1: 'Forrest Gump', Role2: 'Jenny Curran', Role3: 'Lieutenant Dan Taylor',
    Role4: 'Bubba Blue', Role5: 'Mrs. Gump', Role6: 'Young Forrest',
    Role7: 'Elvis Presley', Role8: 'Principal Hancock', Role9: 'Dorothy Harris', Role10: 'Drill Sergeant' },
  { Location: 'The Silence of the Lambs', set: 'movies',
    Role1: 'Clarice Starling', Role2: 'Hannibal Lecter', Role3: 'Buffalo Bill',
    Role4: 'Jack Crawford', Role5: 'Dr. Frederick Chilton', Role6: 'Ardelia Mapp',
    Role7: 'Senator Ruth Martin', Role8: 'Barney Matthews', Role9: 'Multiple Miggs', Role10: 'Catherine Martin' },
  { Location: 'Toy Story', set: 'movies',
    Role1: 'Woody', Role2: 'Buzz Lightyear', Role3: 'Jessie',
    Role4: 'Rex', Role5: 'Hamm', Role6: 'Slinky Dog',
    Role7: 'Mr. Potato Head', Role8: 'Bo Peep', Role9: 'Sarge', Role10: 'Bullseye' },
  { Location: 'Finding Nemo', set: 'movies',
    Role1: 'Nemo', Role2: 'Marlin', Role3: 'Dory',
    Role4: 'Gill', Role5: 'Bloat', Role6: 'Peach',
    Role7: 'Jacques', Role8: 'Gurgle', Role9: 'Bubbles', Role10: 'Nigel' },
  { Location: 'The Hunger Games', set: 'movies',
    Role1: 'Katniss Everdeen', Role2: 'Peeta Mellark', Role3: 'Gale Hawthorne',
    Role4: 'Haymitch Abernathy', Role5: 'Effie Trinket', Role6: 'Caesar Flickerman',
    Role7: 'Cinna', Role8: 'Rue', Role9: 'Finnick Odair', Role10: 'President Snow' },
  { Location: 'Black Panther', set: 'movies',
    Role1: 'T\'Challa', Role2: 'Erik Killmonger', Role3: 'Okoye',
    Role4: 'Shuri', Role5: 'Nakia', Role6: 'M\'Baku',
    Role7: 'Zuri', Role8: 'W\'Kabi', Role9: 'Everett Ross', Role10: 'Queen Ramonda' },
  { Location: 'Parasite', set: 'movies',
    Role1: 'Ki-taek', Role2: 'Ki-woo Kim', Role3: 'Ki-jung Kim',
    Role4: 'Park Dong-ik', Role5: 'Yeon-gyo Park', Role6: 'Moon-gwang',
    Role7: 'Geun-se', Role8: 'Park Da-hye', Role9: 'Park Da-song', Role10: 'Chung-sook' },
  { Location: 'Mad Max: Fury Road', set: 'movies',
    Role1: 'Max Rockatansky', Role2: 'Furiosa', Role3: 'Immortan Joe',
    Role4: 'Nux', Role5: 'The Splendid Angharad', Role6: 'Capable',
    Role7: 'The Dag', Role8: 'Toast the Knowing', Role9: 'Rictus Erectus', Role10: 'Keeper of the Seeds' },
  { Location: 'Avengers: Endgame', set: 'movies',
    Role1: 'Tony Stark', Role2: 'Steve Rogers', Role3: 'Natasha Romanoff',
    Role4: 'Scott Lang', Role5: 'Clint Barton', Role6: 'Thor',
    Role7: 'Nebula', Role8: 'James Rhodes', Role9: 'Carol Danvers', Role10: 'Bruce Banner' },
  { Location: 'Spider-Man: No Way Home', set: 'movies',
    Role1: 'Peter Parker', Role2: 'MJ', Role3: 'Ned Leeds',
    Role4: 'Doctor Strange', Role5: 'Aunt May', Role6: 'Green Goblin',
    Role7: 'Doctor Octopus', Role8: 'Electro', Role9: 'Sandman', Role10: 'The Lizard' },
  { Location: 'Joker', set: 'movies',
    Role1: 'Arthur Fleck', Role2: 'Thomas Wayne', Role3: 'Murray Franklin',
    Role4: 'Penny Fleck', Role5: 'Detective Burke', Role6: 'Detective Garrity',
    Role7: 'Randall', Role8: 'Gary', Role9: 'Sophie Dumond', Role10: 'Alfred' },
  { Location: 'Top Gun: Maverick', set: 'movies',
    Role1: 'Maverick', Role2: 'Rooster', Role3: 'Penny Benjamin',
    Role4: 'Iceman', Role5: 'Hangman', Role6: 'Phoenix',
    Role7: 'Bob', Role8: 'Payback', Role9: 'Fanboy', Role10: 'Admiral Beau Simpson' },
  { Location: 'Everything Everywhere All at Once', set: 'movies',
    Role1: 'Evelyn Wang', Role2: 'Waymond Wang', Role3: 'Joy Wang / Jobu Tupaki',
    Role4: 'Deirdre Beaubeirdre', Role5: 'Alpha Waymond', Role6: 'Gong Gong',
    Role7: 'Chad', Role8: 'Officer Cho', Role9: 'Big Nose', Role10: 'Alpha Evelyn' },
  { Location: 'Oppenheimer', set: 'movies',
    Role1: 'J. Robert Oppenheimer', Role2: 'General Leslie Groves', Role3: 'Jean Tatlock',
    Role4: 'Kitty Oppenheimer', Role5: 'Lewis Strauss', Role6: 'Niels Bohr',
    Role7: 'Edward Teller', Role8: 'Ernest Lawrence', Role9: 'Harry Truman', Role10: 'Werner Heisenberg' },

  // ── Games ─────────────────────────────────────────────────────────────────────
  { Location: 'Among Us', set: 'games',
    Role1: 'Crewmate', Role2: 'Impostor', Role3: 'Engineer',
    Role4: 'Scientist', Role5: 'Guardian Angel', Role6: 'Emergency Button Presser',
    Role7: 'Task Completionist', Role8: 'Vent Watcher', Role9: 'The Sus One', Role10: 'Vent Expert' },
  { Location: 'Minecraft', set: 'games',
    Role1: 'Steve', Role2: 'Alex', Role3: 'Creeper',
    Role4: 'Enderman', Role5: 'Herobrine', Role6: 'Villager',
    Role7: 'Zombie', Role8: 'Skeleton', Role9: 'Spider', Role10: 'Witch' },
  { Location: 'Grand Theft Auto V', set: 'games',
    Role1: 'Michael De Santa', Role2: 'Trevor Philips', Role3: 'Franklin Clinton',
    Role4: 'Lamar Davis', Role5: 'Lester Crest', Role6: 'Jimmy De Santa',
    Role7: 'Amanda De Santa', Role8: 'Devin Weston', Role9: 'Steve Haines', Role10: 'Dave Norton' },
  { Location: 'The Witcher 3', set: 'games',
    Role1: 'Geralt of Rivia', Role2: 'Yennefer of Vengerberg', Role3: 'Triss Merigold',
    Role4: 'Ciri', Role5: 'Dandelion / Jaskier', Role6: 'Vesemir',
    Role7: 'Gaunter O\'Dimm', Role8: 'Eredin', Role9: 'Emhyr var Emreis', Role10: 'Avallac\'h' },
  { Location: 'Red Dead Redemption 2', set: 'games',
    Role1: 'Arthur Morgan', Role2: 'Dutch van der Linde', Role3: 'John Marston',
    Role4: 'Micah Bell', Role5: 'Hosea Matthews', Role6: 'Javier Escuella',
    Role7: 'Charles Smith', Role8: 'Sadie Adler', Role9: 'Abigail Roberts', Role10: 'Bill Williamson' },
  { Location: 'God of War', set: 'games',
    Role1: 'Kratos', Role2: 'Atreus', Role3: 'Freya',
    Role4: 'Baldur', Role5: 'Thor', Role6: 'Odin',
    Role7: 'Mimir', Role8: 'Brok', Role9: 'Sindri', Role10: 'Tyr' },
  { Location: 'The Last of Us', set: 'games',
    Role1: 'Joel Miller', Role2: 'Ellie Williams', Role3: 'Tess',
    Role4: 'Marlene', Role5: 'Tommy Miller', Role6: 'Sam',
    Role7: 'Henry', Role8: 'Bill', Role9: 'David', Role10: 'Abby' },
  { Location: 'Elden Ring', set: 'games',
    Role1: 'Tarnished', Role2: 'Malenia Blade of Miquella', Role3: 'General Radahn',
    Role4: 'Rennala Queen of the Full Moon', Role5: 'Godfrey First Elden Lord', Role6: 'Morgott the Omen King',
    Role7: 'Queen Marika', Role8: 'Fia', Role9: 'Melina', Role10: 'Blaidd the Half-Wolf' },
  { Location: 'Cyberpunk 2077', set: 'games',
    Role1: 'V', Role2: 'Johnny Silverhand', Role3: 'Jackie Welles',
    Role4: 'Judy Alvarez', Role5: 'Panam Palmer', Role6: 'River Ward',
    Role7: 'Goro Takemura', Role8: 'Rogue Amendiares', Role9: 'Evelyn Parker', Role10: 'T-Bug' },
  { Location: 'Halo', set: 'games',
    Role1: 'Master Chief', Role2: 'Cortana', Role3: 'The Arbiter',
    Role4: 'Sergeant Johnson', Role5: 'Captain Keyes', Role6: 'Guilty Spark',
    Role7: 'The Gravemind', Role8: 'Commander Miranda Keyes', Role9: 'Noble Six', Role10: 'Sgt. Forge' },
  { Location: 'Overwatch', set: 'games',
    Role1: 'Tracer', Role2: 'Reaper', Role3: 'Widowmaker',
    Role4: 'Pharah', Role5: 'Reinhardt', Role6: 'Mercy',
    Role7: 'Hanzo', Role8: 'Genji', Role9: 'D.Va', Role10: 'Soldier 76' },
  { Location: 'Valorant', set: 'games',
    Role1: 'Jett', Role2: 'Reyna', Role3: 'Sage',
    Role4: 'Sova', Role5: 'Phoenix', Role6: 'Brimstone',
    Role7: 'Viper', Role8: 'Cypher', Role9: 'Killjoy', Role10: 'Chamber' },
  { Location: 'Fortnite', set: 'games',
    Role1: 'Jonesy', Role2: 'Peely', Role3: 'Drift',
    Role4: 'Raven', Role5: 'Fishstick', Role6: 'Brite Bomber',
    Role7: 'Skull Trooper', Role8: 'The Foundation', Role9: 'The Visitor', Role10: 'Midas' },
  { Location: 'Apex Legends', set: 'games',
    Role1: 'Wraith', Role2: 'Bloodhound', Role3: 'Gibraltar',
    Role4: 'Lifeline', Role5: 'Bangalore', Role6: 'Pathfinder',
    Role7: 'Octane', Role8: 'Wattson', Role9: 'Caustic', Role10: 'Loba' },
  { Location: 'Counter-Strike', set: 'games',
    Role1: 'Entry Fragger', Role2: 'AWPer', Role3: 'In-Game Leader',
    Role4: 'Support Player', Role5: 'Lurker', Role6: 'Rifler',
    Role7: 'Bomb Carrier', Role8: 'Site Anchor', Role9: 'CT Defender', Role10: 'Bomb Defuser' },
  { Location: 'Dark Souls', set: 'games',
    Role1: 'Chosen Undead', Role2: 'Solaire of Astora', Role3: 'Siegmeyer of Catarina',
    Role4: 'Gwyn Lord of Cinder', Role5: 'Sif the Great Grey Wolf', Role6: 'Artorias the Abysswalker',
    Role7: 'Ornstein', Role8: 'Executioner Smough', Role9: 'Kingseeker Frampt', Role10: 'Gwyndolin' },
  { Location: 'Final Fantasy VII', set: 'games',
    Role1: 'Cloud Strife', Role2: 'Tifa Lockhart', Role3: 'Aerith Gainsborough',
    Role4: 'Barret Wallace', Role5: 'Sephiroth', Role6: 'Red XIII',
    Role7: 'Cid Highwind', Role8: 'Yuffie Kisaragi', Role9: 'Vincent Valentine', Role10: 'Reno' },
  { Location: 'Portal 2', set: 'games',
    Role1: 'Chell', Role2: 'GLaDOS', Role3: 'Wheatley',
    Role4: 'Cave Johnson', Role5: 'Atlas', Role6: 'P-body',
    Role7: 'The Announcer', Role8: 'Turret', Role9: 'Caroline', Role10: 'Defective Turret' },
  { Location: 'The Legend of Zelda: BotW', set: 'games',
    Role1: 'Link', Role2: 'Zelda', Role3: 'Calamity Ganon',
    Role4: 'Mipha', Role5: 'Daruk', Role6: 'Revali',
    Role7: 'Urbosa', Role8: 'Impa', Role9: 'Purah', Role10: 'Robbie' },
  { Location: 'Super Mario', set: 'games',
    Role1: 'Mario', Role2: 'Luigi', Role3: 'Princess Peach',
    Role4: 'Bowser', Role5: 'Yoshi', Role6: 'Toad',
    Role7: 'Wario', Role8: 'Donkey Kong', Role9: 'Rosalina', Role10: 'Bowser Jr.' },
  { Location: 'Mortal Kombat', set: 'games',
    Role1: 'Scorpion', Role2: 'Sub-Zero', Role3: 'Liu Kang',
    Role4: 'Kitana', Role5: 'Raiden', Role6: 'Shao Kahn',
    Role7: 'Johnny Cage', Role8: 'Sonya Blade', Role9: 'Jade', Role10: 'Kano' },
  { Location: 'Resident Evil', set: 'games',
    Role1: 'Leon S. Kennedy', Role2: 'Claire Redfield', Role3: 'Chris Redfield',
    Role4: 'Jill Valentine', Role5: 'Ada Wong', Role6: 'Albert Wesker',
    Role7: 'Mr. X', Role8: 'Lady Dimitrescu', Role9: 'Ethan Winters', Role10: 'Nemesis' },
  { Location: 'Baldur\'s Gate 3', set: 'games',
    Role1: 'Shadowheart', Role2: 'Astarion', Role3: 'Gale',
    Role4: 'Lae\'zel', Role5: 'Wyll', Role6: 'Karlach',
    Role7: 'Halsin', Role8: 'Minthara', Role9: 'Jaheira', Role10: 'Minsc' },
  { Location: 'Stardew Valley', set: 'games',
    Role1: 'The Farmer', Role2: 'Harvey', Role3: 'Penny',
    Role4: 'Leah', Role5: 'Emily', Role6: 'Haley',
    Role7: 'Shane', Role8: 'Sebastian', Role9: 'Sam', Role10: 'Elliott' },
  { Location: 'Hollow Knight', set: 'games',
    Role1: 'The Knight', Role2: 'Hornet', Role3: 'Quirrel',
    Role4: 'Grimm', Role5: 'Zote the Mighty', Role6: 'Cornifer',
    Role7: 'Elderbug', Role8: 'The Nailsmith', Role9: 'White Lady', Role10: 'Monomon the Teacher' },
  { Location: 'Street Fighter', set: 'games',
    Role1: 'Ryu', Role2: 'Ken Masters', Role3: 'Chun-Li',
    Role4: 'Guile', Role5: 'Blanka', Role6: 'Zangief',
    Role7: 'Dhalsim', Role8: 'Cammy', Role9: 'Akuma', Role10: 'M. Bison' },
  { Location: 'Sekiro: Shadows Die Twice', set: 'games',
    Role1: 'Wolf (Sekiro)', Role2: 'Kuro', Role3: 'Emma',
    Role4: 'Isshin Ashina', Role5: 'Genichiro Ashina', Role6: 'The Owl',
    Role7: 'Lady Butterfly', Role8: 'O\'Rin of the Water', Role9: 'Corrupted Monk', Role10: 'Guardian Ape' },
  { Location: 'The Sims 4', set: 'games',
    Role1: 'The Aspiring Artist', Role2: 'The Workaholic', Role3: 'The Neighborhood Gossip',
    Role4: 'The Culinary Genius', Role5: 'The Fitness Fanatic', Role6: 'The Romance Expert',
    Role7: 'The Legacy Heir', Role8: 'The Cheat Code User', Role9: 'The Pool Ladder Remover', Role10: 'The CAS Creator' },
  { Location: 'Genshin Impact', set: 'games',
    Role1: 'The Traveler', Role2: 'Paimon', Role3: 'Venti',
    Role4: 'Zhongli', Role5: 'Raiden Shogun', Role6: 'Hu Tao',
    Role7: 'Kazuha', Role8: 'Ganyu', Role9: 'Nahida', Role10: 'Furina' },
  { Location: 'World of Warcraft', set: 'games',
    Role1: 'Paladin', Role2: 'Warrior', Role3: 'Mage',
    Role4: 'Druid', Role5: 'Rogue', Role6: 'Hunter',
    Role7: 'Priest', Role8: 'Warlock', Role9: 'Shaman', Role10: 'Death Knight' },

  // ── Programming ───────────────────────────────────────────────────────────────
  { Location: 'Python', set: 'programming',
    Role1: 'Data Scientist', Role2: 'Machine Learning Engineer', Role3: 'Django Developer',
    Role4: 'Script Automator', Role5: 'Flask API Builder', Role6: 'NumPy Power User',
    Role7: 'Pip Manager', Role8: 'Jupyter Notebook Analyst', Role9: 'Beginner Who Swears By It', Role10: 'Virtual Env Creator' },
  { Location: 'JavaScript', set: 'programming',
    Role1: 'React Developer', Role2: 'Node.js Backend Dev', Role3: 'TypeScript Convert',
    Role4: 'Frontend Engineer', Role5: 'Full-Stack Dev', Role6: 'npm Script Runner',
    Role7: 'Async/Await Master', Role8: 'Callback Hell Survivor', Role9: 'ESLint Enforcer', Role10: 'Webpack Configurer' },
  { Location: 'Git', set: 'programming',
    Role1: 'Commit Message Author', Role2: 'Branch Creator', Role3: 'Merge Conflict Resolver',
    Role4: 'Pull Request Reviewer', Role5: 'Force Push Regrettor', Role6: 'Rebase Enthusiast',
    Role7: 'Git Blame Runner', Role8: 'Cherry Picker', Role9: 'Repository Maintainer', Role10: 'Detached HEAD Survivor' },
  { Location: 'Docker', set: 'programming',
    Role1: 'Container Builder', Role2: 'Image Publisher', Role3: 'Compose Orchestrator',
    Role4: 'Dockerfile Optimizer', Role5: 'Registry Manager', Role6: 'Volume Mounter',
    Role7: 'Network Architect', Role8: 'Port Mapper', Role9: 'Dev Environment Owner', Role10: 'Layer Cacher' },
  { Location: 'Linux', set: 'programming',
    Role1: 'Terminal Power User', Role2: 'Bash Scripter', Role3: 'Kernel Compiler',
    Role4: 'Sysadmin', Role5: 'Vim User', Role6: 'Package Manager',
    Role7: 'SSH Connector', Role8: 'Permission Enforcer', Role9: 'Cron Job Scheduler', Role10: 'Process Killer (kill -9)' },
  { Location: 'React', set: 'programming',
    Role1: 'Component Builder', Role2: 'Custom Hook Creator', Role3: 'State Manager',
    Role4: 'JSX Writer', Role5: 'Props Driller', Role6: 'Redux User',
    Role7: 'Context API Fan', Role8: 'Performance Optimizer', Role9: 'Next.js Developer', Role10: 'Styled Components User' },
  { Location: 'SQL', set: 'programming',
    Role1: 'Database Administrator', Role2: 'Query Optimizer', Role3: 'Schema Designer',
    Role4: 'Index Builder', Role5: 'JOIN Master', Role6: 'Stored Procedure Writer',
    Role7: 'Data Analyst', Role8: 'ETL Developer', Role9: 'Transaction Manager', Role10: 'Backup & Recovery Expert' },
  { Location: 'AWS', set: 'programming',
    Role1: 'EC2 Instance Manager', Role2: 'S3 Bucket Owner', Role3: 'Lambda Function Writer',
    Role4: 'IAM Policy Creator', Role5: 'VPC Architect', Role6: 'CloudFormation Wizard',
    Role7: 'Cost Optimizer', Role8: 'RDS Admin', Role9: 'CloudWatch Monitor', Role10: 'SQS Queue Manager' },
  { Location: 'Rust', set: 'programming',
    Role1: 'Memory Safety Enforcer', Role2: 'Borrow Checker Fighter', Role3: 'Systems Programmer',
    Role4: 'CLI Tool Builder', Role5: 'WASM Compiler', Role6: 'Cargo Package Manager',
    Role7: 'Lifetime Annotator', Role8: 'Trait Implementor', Role9: 'Embedded Engineer', Role10: 'Evangelizer' },
  { Location: 'Kubernetes', set: 'programming',
    Role1: 'Pod Scheduler', Role2: 'Helm Chart Writer', Role3: 'Namespace Manager',
    Role4: 'Ingress Controller', Role5: 'ConfigMap Creator', Role6: 'Node Autoscaler',
    Role7: 'RBAC Policy Maker', Role8: 'Service Mesh Architect', Role9: 'etcd Admin', Role10: 'kubectl Power User' },
  { Location: 'C++', set: 'programming',
    Role1: 'Memory Leak Hunter', Role2: 'Template Metaprogrammer', Role3: 'Game Engine Developer',
    Role4: 'Pointer Arithmetician', Role5: 'STL Expert', Role6: 'Compiler Optimizer',
    Role7: 'Build System Tamer', Role8: 'RAII Practitioner', Role9: 'Legacy Code Maintainer', Role10: 'Performance Chaser' },
  { Location: 'TypeScript', set: 'programming',
    Role1: 'Interface Definer', Role2: 'Type Guard Writer', Role3: 'Generics Expert',
    Role4: 'tsconfig Tweaker', Role5: 'Strict Mode Enforcer', Role6: 'Declaration File Author',
    Role7: 'Discriminated Union User', Role8: 'Utility Type Master', Role9: 'Migration Expert', Role10: 'Compile Error Fixer' },
  { Location: 'Vim', set: 'programming',
    Role1: 'Normal Mode Resident', Role2: 'Insert Mode Visitor', Role3: 'Macro Recorder',
    Role4: '.vimrc Optimizer', Role5: 'Plugin Master', Role6: 'Register Expert',
    Role7: 'Split Window Manager', Role8: 'Search & Replace Wizard', Role9: 'User Who Can\'t Exit', Role10: ':wq Knower' },
  { Location: 'VS Code', set: 'programming',
    Role1: 'Extension Installer', Role2: 'Theme Switcher', Role3: 'IntelliSense Relyer',
    Role4: 'Multi-Cursor Master', Role5: 'Integrated Terminal User', Role6: 'Snippet Creator',
    Role7: 'Debugger User', Role8: 'Git Integration Fan', Role9: 'Workspace Configurator', Role10: 'GitHub Copilot User' },
  { Location: 'MongoDB', set: 'programming',
    Role1: 'Document Designer', Role2: 'Aggregation Pipeline Builder', Role3: 'Index Optimizer',
    Role4: 'Replica Set Manager', Role5: 'Atlas Cloud User', Role6: 'Mongoose Schema Definer',
    Role7: 'Sharding Architect', Role8: 'Query Optimizer', Role9: 'Data Migrator', Role10: 'BSON Expert' },
  { Location: 'Redis', set: 'programming',
    Role1: 'Cache Layer Manager', Role2: 'Session Store Manager', Role3: 'Pub/Sub Broker',
    Role4: 'Rate Limiter', Role5: 'Leaderboard Builder', Role6: 'Queue Worker',
    Role7: 'Key Expiry Expert', Role8: 'Cluster Operator', Role9: 'Data Structure Expert', Role10: 'Persistence Configurator' },
  { Location: 'GraphQL', set: 'programming',
    Role1: 'Schema Definer', Role2: 'Resolver Writer', Role3: 'Mutation Handler',
    Role4: 'Subscription Manager', Role5: 'Apollo Client User', Role6: 'Type Generator',
    Role7: 'Federation Architect', Role8: 'DataLoader Expert', Role9: 'N+1 Problem Solver', Role10: 'REST Migration Expert' },
  { Location: 'Terraform', set: 'programming',
    Role1: 'Infrastructure Coder', Role2: 'State File Manager', Role3: 'Module Writer',
    Role4: 'Provider Configurer', Role5: 'Plan Reviewer', Role6: 'Apply Executor',
    Role7: 'Remote Backend User', Role8: 'Workspace Manager', Role9: 'Drift Detector', Role10: 'Variable Injector' },
  { Location: 'Java', set: 'programming',
    Role1: 'Spring Boot Developer', Role2: 'Maven/Gradle Builder', Role3: 'JVM Tuner',
    Role4: 'Interface Implementor', Role5: 'Checked Exception Handler', Role6: 'Design Pattern Applier',
    Role7: 'Enterprise Architect', Role8: 'Android Developer', Role9: 'Verbose Typer', Role10: 'Boilerplate Writer' },
  { Location: 'Go', set: 'programming',
    Role1: 'Goroutine Spawner', Role2: 'Channel Communicator', Role3: 'Error Handler',
    Role4: 'Binary Builder', Role5: 'Interface Satisfier', Role6: 'gRPC Developer',
    Role7: 'Standard Library Purist', Role8: 'HTTP Server Writer', Role9: 'Go Modules Manager', Role10: 'Minimalist Developer' },
];

module.exports = BUILTIN_LOCATIONS;
